db.user=${DB_USER:admin}
db.password=${DB_PASSWORD:password}
db.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:finalProject}?rewriteBatchedInserts=true
changelog=classpath:db/changelog/changelog.xml
secret=${SECRET}
batchSize = 75